KiemTra_LuChiTam/Controllers/SinhVienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KiemTra_LuChiTam.Models;

namespace KiemTra_LuChiTam.Controllers
{
    public class SinhVienController : Controller
    {
        // GET: SinhVien
        DataDataContext data = new DataDataContext();
        public ActionResult Index()
        {
            var all_sinhvien = from tt in data.SinhViens select tt;
            return View(all_sinhvien);
        }

        public ActionResult Details(int id)
        {
            var D_sinhvien = data.SinhViens.Where(m => Convert.ToInt32(m.MaSV) == id).First();
            return View(D_sinhvien);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, SinhVien sv)
        {
            var E_masv = collection["masv"];
            var E_hoten = collection["hoten"];
            var E_gioitinh = collection["gioitinh"];
            var E_ngaysinh = Convert.ToDateTime(collection["ngaysinh"]);
            var E_hinh = collection["hinh"];
            var E_manganh = collection["manganh"];
            if (string.IsNullOrEmpty(E_masv))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                sv.MaSV = E_masv;
                sv.HoTen = E_hoten.ToString();
                sv.GioiTinh = E_gioitinh;
                sv.NgaySinh = E_ngaysinh;
                sv.Hinh = E_hinh.ToString();
                sv.MaNganh = E_manganh;
                data.SinhViens.InsertOnSubmit(sv);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }

        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "";
            }
            file.SaveAs(Server.MapPath("~/Content/images/" + file.FileName));
            return "/Content/images/" + file.FileName;
        }

        public ActionResult Edit(int id)
        {
            var E_sinhvien = data.SinhViens.First(m => Convert.ToInt32(m.MaSV) == id);
            return View(E_sinhvien);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var E_sinhvien = data.SinhViens.First(m => Convert.ToInt32(m.MaSV) == id);
            var E_hoten = collection["hoten"];
            var E_gioitinh = collection["gioitinh"];
            var E_ngaysinh = Convert.ToDateTime(collection["ngaysinh"]);
            var E_hinh = collection["hinh"];
            var E_manganh = collection["manganh"];
            E_sinhvien.MaSV = id.ToString();

            if (string.IsNullOrEmpty(E_hoten))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                E_sinhvien.HoTen = E_hoten;
                E_sinhvien.GioiTinh = E_gioitinh;
                E_sinhvien.NgaySinh = E_ngaysinh;
                E_sinhvien.Hinh = E_hinh;
                E_sinhvien.MaNganh = E_manganh;
                UpdateModel(E_sinhvien);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Edit(id);
        }

        public ActionResult Delete(int id)
        {
            var D_sinhvien = data.SinhViens.First(m => Convert.ToInt32(m.MaSV) == id);
            return View(D_sinhvien);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var D_sinhvien = data.SinhViens.Where(m => Convert.ToInt32(m.MaSV) == id).First();
            data.SinhViens.DeleteOnSubmit(D_sinhvien);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }
    }
}

KiemTra_LuChiTam/Views/SinhVien/Create.cshtml
@model KiemTra_LuChiTam.Models.SinhVien

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SinhVien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaSV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hinh, "", new { @class = "text-danger" })
                <input type="file" name="fileUpload" id="fileUpload" accept="image/*"
                       style="display:none;" />
                <input type="button" id="btnUpload" value="Chọn" class="btn btn-success" />
            </div>
        </div>
        @section upload
        {
            <script>
                $(function () {
                    $('#btnUpload').click(function () {
                        $('#fileUpload').trigger('click');
                    });
                });
                $('#fileUpload').change(function () {
                    if (window.FormData !== undefined) {
                        var fileUpload = $('#fileUpload').get(0);
                        var files = fileUpload.files;
                        var formData = new FormData();
                        formData.append('file', files[0]);
                        $.ajax(
                            {
                                type: 'POST',
                                url: '/SinhVien/ProcessUpload',
                                contentType: false,
                                processData: false,
                                data: formData,
                                success: function (urlImage) {

                                    $('#pictureUpload').attr('src', urlImage);
                                    $('#Hinh').val(urlImage);
                                },
                                error: function (err) {
                                    alert('Error ', err.statusText);
                                }
                            });
                    }
                });
            </script>
        }


        <div class="form-group">
            @Html.LabelFor(model => model.MaNganh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaNganh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNganh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KiemTra_LuChiTam/Views/SinhVien/Delete.cshtml
@model KiemTra_LuChiTam.Models.SinhVien

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SinhVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinh)
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.Hinh)" width="300" height="300" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaNganh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNganh)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KiemTra_LuChiTam/Views/SinhVien/Details.cshtml
@model KiemTra_LuChiTam.Models.SinhVien

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SinhVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinh)
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.Hinh)" width="300" height="300" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaNganh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNganh)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaSV }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KiemTra_LuChiTam/Views/SinhVien/Edit.cshtml
@model KiemTra_LuChiTam.Models.SinhVien

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>SinhVien</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaSV)

    <div class="form-group">
        @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <strong>Hình</strong>
            @Html.EditorFor(model => model.Hinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Hinh, "", new { @class = "text-danger" })
            <input type="file" name="fileUpload" id="fileUpload" accept="image/*"
                   style="display:none;" />
            <input type="button" id="btnUpload" value="Chọn" class="btn btn-success" />
            <img src="@Model.Hinh" id="pictureUpload" />
        </div>
    </div>
    @section upload
                        {
        <script>
            $(function () {
                $('#btnUpload').click(function () {
                    $('#fileUpload').trigger('click');
                });
            });
            $('#fileUpload').change(function () {
                if (window.FormData !== undefined) {
                    var fileUpload = $('#fileUpload').get(0);
                    var files = fileUpload.files;
                    var formData = new FormData();
                    formData.append('file', files[0]);

                    $.ajax(
                        {
                            type: 'POST',
                            url: '/SinhVien/ProcessUpload',
                            contentType: false,
                            processData: false, data: formData,
                            success: function (urlImage) {

                                $('#pictureUpload').attr('src', urlImage);
                                $('#Hinh').val(urlImage);
                            },
                            error: function (err) {
                                alert('Error ', err.statusText);
                            }
                        });
                }
            });
        </script>
    }

    <div class="form-group">
        @Html.LabelFor(model => model.MaNganh, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaNganh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaNganh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KiemTra_LuChiTam/Views/SinhVien/Index.cshtml
@model IEnumerable<KiemTra_LuChiTam.Models.SinhVien>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>THÔNG TIN SINH VIEN</h2>
<p>
    @Html.ActionLink("Create New", "Create", "SinhVien")
</p>
<table class="table">
    <tr>
        <th> Mã Sinh Viên </th>
        <th> Họ Tên</th>
        <th> Giới Tính </th>
        <th> Ngày Sinh</th>
        <th> Hình </th>
        <th> Mã Ngành</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.MaSV)</td>
            <td>@Html.DisplayFor(modelItem => item.HoTen)</td>
            <td>@Html.DisplayFor(modelItem => item.GioiTinh)</td>
            <td>@Html.DisplayFor(modelItem => item.NgaySinh)</td>
            <td><img src="@item.Hinh" width="300" height="300" /></td>
            <td>@Html.DisplayFor(modelItem => item.MaNganh)</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.MaSV }) |
                @Html.ActionLink("Details", "Details", new { id = item.MaSV }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.MaSV })
            </td>
        </tr>
    }
</table>